services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: 
      - .env
    volumes:
      - .:/src/app
      - /src/app/node_modules
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: store_mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - db_data:/data/db

volumes:
  db_data:
